packages:
  - tests
  - tests/intended-app
  - packages/console-shared-ts
  - packages/wallet-console-shared-ts
  - packages/wallet-console-server-ts
  - packages/console-server-ts
  - voiceId
  - apps/seams-site
  - apps/wallet-console
nodeLinker: hoisted
verifyDepsBeforeRun: false
allowBuilds:
  bufferutil: true
  esbuild: true
  sharp: true
  utf-8-validate: true
  workerd: true
