import { expect, test } from '@playwright/test';
import { readFileSync } from 'node:fs';
import { buildTenantRootIdentityFromAuthenticatedDeploymentV1 } from '../../packages/shared-ts/src/tenant-root/tenantRootIdentity';
import {
  buildTenantRootOperationRecordV1,
  canonicalTenantRootOperationRecordJsonV1,
  parseTenantRootOperationRecordV1,
  tenantRootOperationDigestB64uV1,
  tenantRootOperationFollowsGovernanceV1,
  TENANT_ROOT_RESTORE_ROLE_IMPORT_KEY_ISSUE_OPERATION_KIND_V1,
  type TenantRootOperationKindV1,
  type TenantRootOperationRecordInputV1,
  type TenantRootOperationSubjectV1,
  type TenantRootRestoreRoleImportKeyIssueOperationInputV1,
} from '../../packages/shared-ts/src/tenant-root/tenantRootOperationRecord';

type ActiveTenantRootOperationRecordInputV1 = Exclude<
  TenantRootOperationRecordInputV1,
  { readonly operationKind: 'tenant_root_restore_role_import_key_issue_v1' }
>;

/**
 * The console builds these records; the Rust control plane hashes them. The
 * fixtures are generated by
 * `cargo test -p router-ab-core --test tenant_root_operation_fixtures`
 * (regenerate with UPDATE_TENANT_ROOT_OPERATION_FIXTURES=1).
 */
const FIXTURES = JSON.parse(
  readFileSync(
    new URL(
      '../../crates/router-ab-core/tests/fixtures/tenant-root-operation/records.json',
      import.meta.url,
    ),
    'utf8',
  ),
) as {
  readonly records: readonly {
    readonly operationKind: TenantRootOperationKindV1;
    readonly canonicalJson: string;
    readonly digestB64u: string;
  }[];
};

const IDENTITY_WIRE = {
  orgId: 'org-1',
  projectId: 'project-2',
  envId: 'production',
  signingRootId: 'root-main',
  signingRootVersion: 'v3',
} as const;

const IDENTITY_DIGEST_B64U = 'nF1YOuRpN5POO1FZDHiGUboN9MIzmyW4RnZmX85Eqos';
const CUSTODY_LINEAGE_B64U = 'MTExMTExMTExMTExMTExMQ';
const GOVERNANCE_DIGEST_B64U = 'hUXBekkP6CYYQtt4VJAzSMt0jTshXPte-Te5Q0uBKpc';
const ROOT_COMMITMENT_B64U = '6IKxMQFrUsHTM3CAGHz3aEI-_Mu1F7tJWrgSxBYP9E4';
const RECIPIENT_PAIR_DIGEST_B64U = 'mpqampqampqampqampqampqampqampqampqampqampo';
const RECOVERY_SET_ID_B64U = 'QUFBQUFBQUFBQUFBQUFBQQ';
const RESTORE_NONCE_B64U = 'UVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVFRUVE';
const RESTORE_MANIFEST_DIGEST_B64U = 'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE';
const RESTORE_DESTINATION_FINGERPRINT_B64U = 'cXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXFxcXE';
const RESTORE_SESSION_ID_B64U = 'gYGBgYGBgYGBgYGBgYGBgQ';

const ISSUED_AT = '2026-09-05T11:58:00.000Z';
const EXPIRES_AT = '2026-09-05T12:05:00.000Z';
const RESTORE_EXPIRES_AT = '2026-09-05T12:03:00.000Z';

function identity() {
  const result = buildTenantRootIdentityFromAuthenticatedDeploymentV1(IDENTITY_WIRE);
  if (!result.ok) throw new Error('identity fixture is invalid');
  return result.value;
}

function input(
  operationKind: ActiveTenantRootOperationRecordInputV1['operationKind'],
  subject: TenantRootOperationSubjectV1,
  overrides: Partial<ActiveTenantRootOperationRecordInputV1> = {},
): ActiveTenantRootOperationRecordInputV1 {
  return {
    operationKind,
    identity: identity(),
    tenantRootIdentityDigest: IDENTITY_DIGEST_B64U,
    custodyLineageId: CUSTODY_LINEAGE_B64U,
    expectedLifecycleRevision: 7,
    recoveryGovernanceDigest: GOVERNANCE_DIGEST_B64U,
    subject,
    requesterActorId: 'owner-1',
    idempotencyKey: 'idempotency-1',
    issuedAt: ISSUED_AT,
    expiresAt: EXPIRES_AT,
    expectedRootCommitment: ROOT_COMMITMENT_B64U,
    ...overrides,
  };
}

function restoreInput(): TenantRootRestoreRoleImportKeyIssueOperationInputV1 {
  return {
    operationKind: TENANT_ROOT_RESTORE_ROLE_IMPORT_KEY_ISSUE_OPERATION_KIND_V1,
    identity: identity(),
    tenantRootIdentityDigest: IDENTITY_DIGEST_B64U,
    custodyLineageId: CUSTODY_LINEAGE_B64U,
    subject: { kind: 'recovery_set', recoverySetId: RECOVERY_SET_ID_B64U },
    role: 'deriver_a',
    requesterActorId: 'owner-1',
    idempotencyKey: 'restore-operation-1',
    nonceB64u: RESTORE_NONCE_B64U,
    issuedAt: ISSUED_AT,
    expiresAt: RESTORE_EXPIRES_AT,
    manifestDigestB64u: RESTORE_MANIFEST_DIGEST_B64U,
    destinationFingerprintB64u: RESTORE_DESTINATION_FINGERPRINT_B64U,
    restoreSessionIdB64u: RESTORE_SESSION_ID_B64U,
    importKeyId: 'restore-import-key-1',
    generation: 1,
  };
}

function build(inputValue: TenantRootOperationRecordInputV1) {
  const result = buildTenantRootOperationRecordV1(inputValue);
  if (!result.ok) throw new Error(`record rejected: ${JSON.stringify(result.error)}`);
  return result.record;
}

test('produces the exact canonical bytes and digests the Rust control plane expects', async () => {
  const cases: Record<string, TenantRootOperationRecordInputV1> = {
    tenant_root_operational_share_rotation_v1: input('tenant_root_operational_share_rotation_v1', {
      kind: 'tenant_root',
    }),
    tenant_root_recovery_recipient_pair_enroll_v1: input(
      'tenant_root_recovery_recipient_pair_enroll_v1',
      { kind: 'recipient_pair', recipientPairDigest: RECIPIENT_PAIR_DIGEST_B64U },
    ),
    tenant_root_recovery_role_package_download_v1: input(
      'tenant_root_recovery_role_package_download_v1',
      { kind: 'recovery_set', recoverySetId: RECOVERY_SET_ID_B64U },
      { role: 'deriver_b', expiresAt: '2026-09-05T12:02:00.000Z' },
    ),
    tenant_root_source_lineage_retire_v1: input('tenant_root_source_lineage_retire_v1', {
      kind: 'tenant_root',
    }),
    tenant_root_restore_role_import_key_issue_v1: restoreInput(),
  };

  expect(FIXTURES.records.length).toBe(Object.keys(cases).length);
  for (const fixture of FIXTURES.records) {
    const record = build(cases[fixture.operationKind]!);
    expect(canonicalTenantRootOperationRecordJsonV1(record)).toBe(fixture.canonicalJson);
    expect(await tenantRootOperationDigestB64uV1(record)).toBe(fixture.digestB64u);
  }
});

test('changing any bound field changes the operation digest', async () => {
  const base = build(input('tenant_root_operational_share_rotation_v1', { kind: 'tenant_root' }));
  const baseDigest = await tenantRootOperationDigestB64uV1(base);

  const variants = [
    build(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        { expectedLifecycleRevision: 8 },
      ),
    ),
    build(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        { requesterActorId: 'owner-2' },
      ),
    ),
    build(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        { idempotencyKey: 'idempotency-2' },
      ),
    ),
    build(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        { custodyLineageId: 'MjIyMjIyMjIyMjIyMjIyMg' },
      ),
    ),
  ];
  for (const variant of variants) {
    expect(await tenantRootOperationDigestB64uV1(variant)).not.toBe(baseDigest);
  }
});

test('rejects records whose subject, role, or lifetime does not match the operation', () => {
  // A role-local operation must name its role.
  expect(
    buildTenantRootOperationRecordV1(
      input('tenant_root_recovery_role_package_download_v1', {
        kind: 'recovery_set',
        recoverySetId: RECOVERY_SET_ID_B64U,
      }),
    ),
  ).toEqual({ ok: false, error: { kind: 'role_does_not_match_operation' } });

  // A tenant-root operation may not name one.
  expect(
    buildTenantRootOperationRecordV1(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        {
          role: 'deriver_a',
        },
      ),
    ),
  ).toEqual({ ok: false, error: { kind: 'role_does_not_match_operation' } });

  // A recipient-pair operation cannot claim a tenant-root subject.
  expect(
    buildTenantRootOperationRecordV1(
      input('tenant_root_recovery_recipient_pair_enroll_v1', { kind: 'tenant_root' }),
    ),
  ).toEqual({ ok: false, error: { kind: 'subject_does_not_match_operation' } });

  // A ciphertext download authorization may not outlive five minutes.
  expect(
    buildTenantRootOperationRecordV1(
      input(
        'tenant_root_recovery_role_package_download_v1',
        { kind: 'recovery_set', recoverySetId: RECOVERY_SET_ID_B64U },
        { role: 'deriver_a', expiresAt: '2026-09-05T12:04:00.000Z' },
      ),
    ),
  ).toEqual({ ok: false, error: { kind: 'lifetime_exceeds_maximum', maximumMs: 300_000 } });

  // A timestamp that is not a real instant is not canonical.
  expect(
    buildTenantRootOperationRecordV1(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        {
          issuedAt: '2026-02-31T00:00:00.000Z',
        },
      ),
    ),
  ).toEqual({ ok: false, error: { kind: 'timestamp_not_canonical', field: 'issuedAt' } });

  expect(
    buildTenantRootOperationRecordV1(
      input(
        'tenant_root_operational_share_rotation_v1',
        { kind: 'tenant_root' },
        {
          expiresAt: ISSUED_AT,
        },
      ),
    ),
  ).toEqual({ ok: false, error: { kind: 'expiry_not_after_issue' } });
});

test('names exactly the four operations that follow recovery governance', () => {
  const governed: TenantRootOperationKindV1[] = [
    'tenant_root_recovery_governance_change_v1',
    'tenant_root_recovery_recipient_pair_enroll_v1',
    'tenant_root_recovery_recipient_pair_replace_v1',
    'tenant_root_source_lineage_retire_v1',
  ];
  for (const kind of governed) {
    expect(tenantRootOperationFollowsGovernanceV1(kind)).toBe(true);
  }
  for (const kind of [
    'tenant_root_operational_share_rotation_v1',
    'tenant_root_recovery_backup_create_v1',
    'tenant_root_recovery_role_package_download_v1',
    'tenant_root_restore_activate_v1',
  ] as const) {
    expect(tenantRootOperationFollowsGovernanceV1(kind)).toBe(false);
  }
});

test('restore role-import issuance binds the destination without active-root state', () => {
  const built = buildTenantRootOperationRecordV1(restoreInput());

  expect(built.ok).toBe(true);
  if (!built.ok) return;
  expect('expectedLifecycleRevision' in built.record).toBe(false);
  expect('recoveryGovernanceDigest' in built.record).toBe(false);
  expect('expectedRootCommitment' in built.record).toBe(false);
  const canonical = canonicalTenantRootOperationRecordJsonV1(built.record);
  expect(parseTenantRootOperationRecordV1(canonical)).toEqual(built.record);
  expect(
    parseTenantRootOperationRecordV1(
      JSON.stringify({ ...built.record, expectedLifecycleRevision: 7 }),
    ),
  ).toBeNull();
});
